version: '3.7'

services:
  nest-app:
    container_name: nest-app
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: production
    volumes:
      - ../..:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file: .env.production
    depends_on:
      database:
        condition: service_healthy
    networks:
      - webnet
  database:
    container_name: database
    image: postgres:12
    networks:
      - webnet
    env_file: .env.production
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  webnet:
    driver: bridge

volumes:
  pgdata:
